### ISSUE TITLE
problem about the HIFI_Net

### ISSUE THREAD

**Issue by 311311y** [CHELSEA234/HiFi_IFDL#25]
Thank you for your work! When I run HIFI_Net.py

=> loading HRNet pretrained model models/hrnet_w18_small_v2.pth
no pretrain dict length is:  183
pretrained dict length is:  874
weights/HRNet weight-loading succeeds: weights/HRNet/750001.pth
weights/HRNet_params: 6361208
weights/NLCDetection weight-loading succeeds: weights/NLCDetection/750001.pth
weights/NLCDetection_params: 528923

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
The Radius manipul is 0.18607237935066223.
The Radius expansn is 3.101206064224243.
The Radius threshold is 2.2948925495147705.
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

/root/autodl-tmp/HiFi_Net.py:75: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(image_name)
Traceback (most recent call last):
  File "/root/autodl-tmp/HiFi_Net.py", line 215, in <module>
    inference(args.img_path)
  File "/root/autodl-tmp/HiFi_Net.py", line 185, in inference
    res3, prob3 = HiFi.detect(img_path)
  File "/root/autodl-tmp/HiFi_Net.py", line 136, in detect
    img_input = self._transform_image(image_name)
  File "/root/autodl-tmp/HiFi_Net.py", line 75, in _transform_image
    image = imageio.imread(image_name)
  File "/root/miniconda3/lib/python3.8/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 252, in read
    image = self._apply_transforms(
  File "/root/miniconda3/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 335, in _apply_transforms
    meta = self.metadata(index=self._image.tell(), exclude_applied=False)
  File "/root/miniconda3/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 537, in metadata
    if self._image.getexif():
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 1423, in getexif
    self._exif.load_from_fp(self.fp, self.tag_v2._offset)
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 3531, in load_from_fp
    self.fp.seek(offset)
AttributeError: 'NoneType' object has no attribute 'seek'

could  you please tell where is the wrong?

**Comment by CHELSEA234** [comment]
@311311y I have just tested loading the HiFi_Net using https://github.com/CHELSEA234/HiFi_IFDL?tab=readme-ov-file#usage-on-the-detection-and-localization-in-the-hifi-ifdl-dataset 
I do not run into any problem.
![Screenshot 2023-12-19 at 1 34 08 AM](https://github.com/CHELSEA234/HiFi_IFDL/assets/24967323/ab5ecc1b-8e31-4097-9a0a-f61f1bba41c3)
